---
title: "General Information Throughout Years (1995-2000)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(highcharter))
suppressPackageStartupMessages(library(leaflet))
suppressPackageStartupMessages(library(corrplot))
dfnasa <- as.data.frame(nasa)
year1 = slice(dfnasa,1,577,1153,1729,2305,2881,3457,4033,4609,5185,5761,6337)
year2 = slice(dfnasa,6913,7489,8065,8641,9217,9793,10369,10945,11521,12097,12673,13249)
year3 = slice(dfnasa,13825,14401,14977,15553,16129,16705,17281,17857,18433,19009,19585,20161)
year4 = slice(dfnasa,20737,21313,21889,22465,23041,23617,24193,24769,25345,25921,26497,27073)
year5 = slice(dfnasa,27649,28225,28801,29377,29953,30529,31105,31681,32257,32833,33409,33985)
year6 = slice(dfnasa,34561,35137,35713,36289,36865,37441,38017,38593,39169,39745,40321,40897)
```

1995
=======================================================================
Column {data-width=500}
-----------------------------------------------------------------------

### Cloud Coverage

```{r}
highchart() %>%
  hc_xAxis(categories = year1$month) %>% 
  hc_add_series(name = "High Cloud", data = year1$cloudhigh) %>% 
  hc_add_series(name = "Low Cloud", data = year1$cloudlow) %>%
  hc_add_series(name = "Medium Cloud", data = year1$cloudmid) %>%
  hc_add_theme(hc_theme_538())
```

### Temperatures and Ozone

```{r}
highchart() %>%
  hc_xAxis(categories = year1$month) %>% 
  hc_add_series(name = "Temperature", data = year1$temperature) %>% 
  hc_add_series(name = "Surface Temperature", data = year1$surftemp) %>%
  hc_add_series(name = "Ozone", data = year1$ozone) %>%
  hc_add_theme(hc_theme_economist())
```

### Pressure

```{r}
highchart() %>%
  hc_xAxis(categories = year1$month) %>%
  hc_add_series(name = "Pressure", data = year1$pressure) %>%
  hc_add_theme(hc_theme_ffx())
```

1996
=======================================================================
Column {data-width=500}
-----------------------------------------------------------------------

### Cloud Coverage

```{r}
highchart() %>%
  hc_xAxis(categories = year2$month) %>% 
  hc_add_series(name = "High Cloud", data = year2$cloudhigh) %>% 
  hc_add_series(name = "Low Cloud", data = year2$cloudlow) %>%
  hc_add_series(name = "Medium Cloud", data = year2$cloudmid) %>%
  hc_add_theme(hc_theme_538())
```

### Temperatures and Ozone

```{r}
highchart() %>%
  hc_xAxis(categories = year2$month) %>% 
  hc_add_series(name = "Temperature", data = year2$temperature) %>% 
  hc_add_series(name = "Surface Temperature", data = year2$surftemp) %>%
  hc_add_series(name = "Ozone", data = year2$ozone) %>%
  hc_add_theme(hc_theme_economist())
```

### Pressure

```{r}
highchart() %>%
  hc_xAxis(categories = year2$month) %>%
  hc_add_series(name = "Pressure", data = year2$pressure) %>%
  hc_add_theme(hc_theme_ffx())
```

1997
=======================================================================
Column {data-width=500}
-----------------------------------------------------------------------

### Temperatures and Ozone

```{r}
highchart() %>%
  hc_xAxis(categories = year3$month) %>% 
  hc_add_series(name = "High Cloud", data = year3$cloudhigh) %>% 
  hc_add_series(name = "Low Cloud", data = year3$cloudlow) %>%
  hc_add_series(name = "Medium Cloud", data = year3$cloudmid) %>%
  hc_add_theme(hc_theme_538())
```

### Temperatures and Ozone

```{r}
highchart() %>%
  hc_xAxis(categories = year3$month) %>% 
  hc_add_series(name = "Temperature", data = year3$temperature) %>% 
  hc_add_series(name = "Surface Temperature", data = year3$surftemp) %>%
  hc_add_series(name = "Ozone", data = year3$ozone) %>%
  hc_add_theme(hc_theme_economist())
```

### Pressure

```{r}
highchart() %>%
  hc_xAxis(categories = year3$month) %>%
  hc_add_series(name = "Pressure", data = year3$pressure) %>%
  hc_add_theme(hc_theme_ffx())
```

1998
=======================================================================
Column {data-width=500}
-----------------------------------------------------------------------

### Cloud Coverage

```{r}
highchart() %>%
  hc_xAxis(categories = year4$month) %>% 
  hc_add_series(name = "High Cloud", data = year4$cloudhigh) %>% 
  hc_add_series(name = "Low Cloud", data = year4$cloudlow) %>%
  hc_add_series(name = "Medium Cloud", data = year4$cloudmid) %>%
  hc_add_theme(hc_theme_538())
```

### Temperatures and Ozone

```{r}
highchart() %>%
  hc_xAxis(categories = year4$month) %>% 
  hc_add_series(name = "Temperature", data = year4$temperature) %>% 
  hc_add_series(name = "Surface Temperature", data = year4$surftemp) %>%
  hc_add_series(name = "Ozone", data = year4$ozone) %>%
  hc_add_theme(hc_theme_economist())
```

### Pressure

```{r}
highchart() %>%
  hc_xAxis(categories = year4$month) %>%
  hc_add_series(name = "Pressure", data = year4$pressure) %>%
  hc_add_theme(hc_theme_ffx())
```

1999
=======================================================================
Column {data-width=500}
-----------------------------------------------------------------------

### Cloud Coverage

```{r}
highchart() %>%
  hc_xAxis(categories = year5$month) %>% 
  hc_add_series(name = "High Cloud", data = year5$cloudhigh) %>% 
  hc_add_series(name = "Low Cloud", data = year5$cloudlow) %>%
  hc_add_series(name = "Medium Cloud", data = year5$cloudmid) %>%
  hc_add_theme(hc_theme_538())
```

### Temperatures and Ozone

```{r}
highchart() %>%
  hc_xAxis(categories = year5$month) %>% 
  hc_add_series(name = "Temperature", data = year5$temperature) %>% 
  hc_add_series(name = "Surface Temperature", data = year5$surftemp) %>%
  hc_add_series(name = "Ozone", data = year5$ozone) %>%
  hc_add_theme(hc_theme_economist())
```

### Pressure

```{r}
highchart() %>%
  hc_xAxis(categories = year5$month) %>%
  hc_add_series(name = "Pressure", data = year5$pressure) %>%
  hc_add_theme(hc_theme_ffx())
```

2000
=======================================================================
Column {data-width=500}
-----------------------------------------------------------------------

### Cloud Coverage

```{r}
highchart() %>%
  hc_xAxis(categories = year6$month) %>% 
  hc_add_series(name = "High Cloud", data = year6$cloudhigh) %>% 
  hc_add_series(name = "Low Cloud", data = year6$cloudlow) %>%
  hc_add_series(name = "Medium Cloud", data = year6$cloudmid) %>%
  hc_add_theme(hc_theme_538())
```

### Temperatures and Ozone

```{r}
highchart() %>%
  hc_xAxis(categories = year6$month) %>% 
  hc_add_series(name = "Temperature", data = year6$temperature) %>% 
  hc_add_series(name = "Surface Temperature", data = year6$surftemp) %>%
  hc_add_series(name = "Ozone", data = year6$ozone) %>%
  hc_add_theme(hc_theme_economist())
```

### Pressure

```{r}
highchart() %>%
  hc_xAxis(categories = year6$month) %>%
  hc_add_series(name = "Pressure", data = year6$pressure) %>%
  hc_add_theme(hc_theme_ffx())
```

Maps
=======================================================
Column {data-width=500}
-----------------------------------------------------------------------
###Temperature Distribution
```{r}
dflat = dfnasa$lat[1:576]
dflong = dfnasa$long[1:576]

qpal <- colorFactor(c("blue","royalblue","lightskyblue", "yellow","orange","red"), domain = dfnasa$temperature[1:576])

leaflet(slice(dfnasa,1:576)) %>%
  addTiles() %>%
  setView(lng = -90, lat =  10, zoom = 3) %>%
  addCircleMarkers(lat = dflat, lng = dflong,color = ~qpal(temperature),stroke = FALSE, fillOpacity= 0.3,
                    popup = paste("Temperature:", dfnasa$temperature))
```


Column {data-width=500}
-----------------------------------------------------------------------
###Atmospheric Pressure Distribution
```{r}
dflat = dfnasa$lat[1:576]
dflong = dfnasa$long[1:576]

qpal <- colorFactor(c("blue","yellow2","orange","firebrick1"), domain = dfnasa$pressure[1:576])

leaflet(slice(dfnasa,1:576)) %>%
  addTiles() %>%
  setView(lng = -90, lat =  10, zoom = 3) %>%
  addCircleMarkers(lat = dflat, lng = dflong,color = ~qpal(pressure),stroke = FALSE, fillOpacity= 0.5,
                   popup = paste("Pressure:",dfnasa$pressure))
```

Other
=======================================================================

###Correlation Between Variables
```{r}
selected_var <- year1 %>%
  select(cloudhigh,cloudmid,cloudlow,ozone,pressure,temperature,surftemp)
corr_nasa <- cor(selected_var)
corrplot(corr_nasa,method = "number")
```


